# Generated by Django 3.0.7 on 2020-10-09 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='place_image',
        ),
        migrations.AddField(
            model_name='image',
            name='place',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='places.Place', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='places_images', verbose_name='Файл изображения'),
        ),
    ]
