# Generated by Django 3.0.7 on 2020-09-28 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='place',
        ),
        migrations.AddField(
            model_name='image',
            name='place_image',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='place_image', to='places.Place', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
