# Generated by Django 3.0.7 on 2020-07-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='imgs',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
