# Generated by Django 3.0.7 on 2020-08-16 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20200720_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image', models.ImageField(blank=True, upload_to='')),
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place')),
            ],
        ),
    ]
