# Generated by Django 3.0.7 on 2020-09-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20200928_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.PositiveIntegerField(null=True, verbose_name='Порядковый номер'),
        ),
    ]
