# Generated by Django 3.0.7 on 2020-08-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='imgs',
        ),
    ]
