# Generated by Django 3.0.7 on 2020-09-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_place_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
