# Generated by Django 3.0.7 on 2020-09-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20200906_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='place_image',
        ),
    ]
