# Generated by Django 3.0.7 on 2020-09-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_auto_20200912_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='places_images'),
        ),
    ]
