# Generated by Django 3.0.7 on 2020-09-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_auto_20200912_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_id',
        ),
        migrations.AddField(
            model_name='image',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
