# Generated by Django 3.0.7 on 2020-09-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_auto_20200912_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
