# Generated by Django 3.0.7 on 2020-09-13 07:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0019_auto_20200912_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='content',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
