# Generated by Django 3.0.7 on 2020-09-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0022_auto_20200918_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(blank=True, default=models.CharField(max_length=200), max_length=20),
        ),
    ]
