# Generated by Django 3.0.7 on 2020-09-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0025_auto_20200919_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(blank=True, default=False, max_length=20),
        ),
    ]
