# Generated by Django 3.0.7 on 2020-09-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0026_place_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(blank=True, default='place', max_length=20),
        ),
    ]
