# Generated by Django 3.0.7 on 2020-09-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0028_auto_20200919_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=20),
        ),
    ]
